{
 "title": "Database queries",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Products types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT productLine as label, COUNT(productLine) AS total FROM classicmodels.products GROUP BY productLine ORDER BY productLine"
    }
   ]
  },
  {
   "title": "Customers",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT customerName, phone, city FROM classicmodels.customers LIMIT 3 "
    }
   ]
  },
  {
   "title": "Total of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT COUNT(*) FROM classicmodels.customers LIMIT 50 "
    }
   ]
  },
  {
   "title": "Emplyees",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT firstName, lastName, email FROM classicmodels.employees LIMIT 3 "
    }
   ]
  },
  {
   "title": "Total of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT COUNT(*) FROM classicmodels.employees LIMIT 50 "
    }
   ]
  },
  {
   "title": "Customers",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT productName, quantityInStock, buyPrice FROM classicmodels.products LIMIT 3 "
    }
   ]
  },
  {
   "title": "Total of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "classicmodels",
     "rawSql": "SELECT COUNT(*) FROM classicmodels.products LIMIT 50 "
    }
   ]
  }
 ]
}